package de.mannodermaus.kommandah.models

import org.threeten.bp.Duration

sealed class OutputEvent {

  /**
   * An instruction calculated a numerical result
   */
  data class Calc(val instruction: Instruction, val result: Int) : OutputEvent()

  /**
   * An instruction was executed successfully, but without any by-product.
   */
  data class Void(val instruction: Instruction) : OutputEvent()

  /**
   * A log message was generated by the given instruction
   */
  data class Log(val instruction: Instruction, val message: String) : OutputEvent()

  /**
   * An error occurred at the given instruction,
   * and execution was halted because of it.
   */
  data class Error(val instruction: Instruction, val cause: Exception) : OutputEvent()

  object Completed : OutputEvent()
}

data class ExecutionEnvironment(
    val speed: Duration = Duration.ofMillis(100)
)
